// projects.js
// Generated by Portfolio Editor v2.1

window.projects = [
  {
    "id": "embedded-control-poc",
    "name": "Embedded Control System PoC",
    "date": "2024-08",
    "role": "Hardware Developer",
    "types": [
      "technical-design"
    ],
    "shortDesc": "A functional prototype designed to validate sensor logic and mechanical control before final manufacturing.",
    "longDesc": "This project focuses on the prototyping phase of a custom embedded system. I designed and manufactured the initial PCB using CNC isolation milling to quickly test the circuit concepts in the real world.\n\nThe system integrates various complex components, including absolute encoders, EMF sensors, and potentiometers. These inputs are used to control the vertical movement of the machine and manage haptic feedback through vibration motors. The primary goal was to verify component compatibility and refine the firmware logic, bridging the gap between the digital design and the physical final product.",
    "coverImage": "images/PoC-Pcb/PoC-01.jpg",
    "gallery": [
      {
        "type": "image",
        "src": "images/PoC-Pcb/PoC-01.jpg"
      },
      {
        "type": "image",
        "src": "images/PoC-Pcb/PoC-02.jpg"
      },
      {
        "type": "image",
        "src": "images/PoC-Pcb/PoC-03.jpg"
      },
      {
        "type": "image",
        "src": "images/PoC-Pcb/PoC-04.jpg"
      },
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=8g_zKZJrbSY"
      }
    ],
    "links": [],
    "tagline": "PCB Design • C++ • CNC Milling • Sensor Integration • Motor Control"
  },
  {
    "id": "EM-Guided-Surgical-Trainer",
    "name": "EM-Guided Surgical Trainer: Knee Module",
    "role": "Industrial Designer & 3D Modeler",
    "tagline": "Fusion 360 • Blender • 3D Printing • EM Tracking • Mechanical Design",
    "date": "2024-01",
    "types": [
      "technical-design"
    ],
    "shortDesc": "An anatomically accurate, hybrid surgical simulator integrating electromagnetic tracking technology with strict material engineering for signal integrity.",
    "longDesc": "This project is a high-fidelity simulator module developed for arthroscopy training, bridging organic modeling with precision engineering.\n\nHybrid Design Workflow: The realistic anatomical forms of the knee (femur, tibia, patella) were sculpted in Blender using anatomical references. These organic meshes were then integrated into Fusion 360 to design the mechanical articulation, ensuring the assembly replicates the exact kinematics of natural knee movement.\n\nElectromagnetic Compatibility (EMC): A critical constraint of the project was the integration of an electromagnetic tracking system. Since metal components distort magnetic fields and compromise sensor accuracy, the design process required rigorous calculation to maintain electromagnetic transparency. The structure was engineered to be entirely non-ferrous in critical zones to prevent signal interference.\n\nSensor Integration: Each component features custom-designed housing for positioning sensors. These housings are calibrated to ensure the sensors transmit their precise location relative to the central EMF source without any distortion caused by the device's hardware.",
    "coverImage": "images/em-guided/em-guided-01.jpg",
    "gallery": [
      {
        "type": "image",
        "src": "images/em-guided/em-guided-01.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-02.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-03.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-04.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-05.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-06.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-07.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-08.jpg"
      },
      {
        "type": "image",
        "src": "images/em-guided/em-guided-09.jpg"
      }
    ],
    "links": []
  },
  {
    "id": "height-adjustable-chassis-design",
    "name": "Height Adjustable Chassis Mechanism & Sheet Metal Body Design",
    "date": "2023-09",
    "role": "Mechanical Design & Manufacturing",
    "types": [
      "technical-design"
    ],
    "shortDesc": "Design and manufacturing of a mobile chassis system with vertical lift capability using linear actuators, featuring a sigma profile skeleton and sheet metal cladding.",
    "longDesc": "In this project, a height-adjustable mobile machine chassis capable of carrying electronic hardware was manufactured from scratch.\n\nMotion System: Vertical movement (lift) of the chassis was achieved using synchronized electric linear actuators and telescopic rails.\n\nFrame Structure: The supporting body was built using Aluminum Sigma Profiles (T-Slot) for ease of assembly and modularity.\n\nBody Manufacturing: The outer cladding designed in Fusion 360 was shaped via laser cutting and Press Brake Bending, painted, and assembled onto the chassis.\n\nParts Manufacturing: Custom connection parts and plastic components were produced personally using a CNC router and 3D printer.",
    "coverImage": "images/Chassis Mechanism/ChassisMechanism-01.png",
    "gallery": [
      {
        "type": "image",
        "src": "images/Chassis Mechanism/ChassisMechanism-01.png",
              },
      {
        "type": "youtube",
        "src": "https://youtube.com/shorts/b_mTvKPiusM?feature=share",
              }
    ],
    "links": [],
    "tagline": "Fusion 360 • Sheet Metal • Linear Actuators • Sigma Profiles • CNC & 3D Printing"
  },
  {
    "id": "prosthetic-worlds-vr",
    "name": "Prosthetic Worlds – VR Surgery",
    "role": "Simulation Developer",
    "tagline": "VR • Surgical Training • TKA • Medical Sim",
    "date": "2022-11",
    "types": [
      "software",
      "design",
      "simulation"
    ],
    "shortDesc": "A scientifically validated VR training simulation for Total Knee Arthroplasty (TKA), designed to help surgeons practice without patient risk.",
    "longDesc": "Prosthetic Worlds is a VR surgical training experience focused on Total Knee Arthroplasty (TKA). Trainees can walk through each surgical step at their own pace, repeat critical actions, and build confidence in a risk-free environment. In a controlled study with 20 doctors, the group trained with this VR system achieved significantly higher scores in surgical parameters compared to traditional training methods. This project aims to compress years of operating room learning into a structured, measurable VR workflow.",
    "coverImage": "images/Prosthetic Worlds – VR Surgery/Pw-02.jpg",
    "gallery": [
      {
        "type": "image",
        "src": "images/Prosthetic Worlds – VR Surgery/Pw-01.jpg"
      },
      {
        "type": "image",
        "src": "images/Prosthetic Worlds – VR Surgery/Pw-02.jpg"
      },
      {
        "type": "image",
        "src": "images/Prosthetic Worlds – VR Surgery/Pw-03.jpg"
      },
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=sWOdGYnegjY"
      }
    ],
    "links": [
      {
        "label": "Read Research Article (NCBI)",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11596432/pdf/medi-103-e40615.pdf"
      },
      {
        "label": "View on Instagram",
        "url": "https://www.instagram.com/prostheticworlds"
      }
    ]
  },
  {
    "id": "fire-evacuation-sim",
    "name": "Fire Evacuation Digital Twin",
    "role": "Contract Developer (Bespoke Demo)",
    "tagline": "Digital Twin • Lidar Scanning • AR Guidance • Serious Games",
    "date": "2022-10",
    "types": [
      "software",
      "design"
    ],
    "shortDesc": "A custom-built safety training demo where a specific real-world facility was scanned and recreated as a Digital Twin.",
    "longDesc": "Developed as a bespoke proof-of-concept for a client, this project utilizes Lidar scanning to recreate their specific facility 1:1 in Unity. The simulation serves as a specialized training tool where employees must navigate their actual work environment virtually, reacting to procedurally generated fire hazards and following AR-style safety routes.",
    "coverImage": "images/fireIcon.jpg",
    "gallery": [
      {
        "type": "youtube",
        "src": "https://youtu.be/pptgV_zM5ts"
      }
    ],
    "links": []
  },
  {
    "id": "dolmuscu-dayi",
    "name": "Dolmuşçu Dayı",
    "role": "Freelance Developer",
    "tagline": "Game Economy • 2D Animation • Cultural Adaptation",
    "date": "2022-07",
    "types": [
      "software"
    ],
    "shortDesc": "A culturally localized simulation game managing passengers and economy in a chaotic traffic environment.",
    "longDesc": "Developed as a hyper-casual simulation, this project focuses on resource management and multitasking. I handled the entire development pipeline: from 2D sprite animation and UI design to the core game loop involving passenger logic and currency systems. It serves as a strong example of product polishing and cultural localization.",
    "coverImage": "images/DolmusIcon.png",
    "gallery": [
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=oGrix2jcBIw"
      }
    ],
    "links": [
      {
        "label": "App Store",
        "url": "https://apps.apple.com/us/app/dolmu%C5%9F%C3%A7u-day%C4%B1/id1636141841"
      }
    ]
  },
  {
    "id": "redline-drag-racing",
    "name": "Redline Drag Racing",
    "role": "Freelance Developer",
    "tagline": "Vehicle Physics • Kinematics • UI/UX • Android",
    "date": "2022-05",
    "types": [
      "software"
    ],
    "shortDesc": "2D competitive racing simulator focusing on launch kinematics, transmission timing, and vehicle tuning.",
    "longDesc": "This project focuses on the mathematics of drag racing. I programmed the vehicle physics including torque curves, tire friction models, and a precision-based manual transmission system. The game requires players to master reaction times (ms) and shift points, demanding a highly responsive UI and input handling system.",
    "coverImage": "images/DragIcon.jpg",
    "gallery": [
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=XFWho0Bv_xU"
      }
    ],
    "links": [
      {
        "label": "Google Play",
        "url": "https://play.google.com/store/apps/details?id=com.okkagames.redlinedragracing&hl=en"
      }
    ]
  },
  {
    "id": "dragon-faya",
    "name": "Dragon Faya",
    "role": "Freelance Developer",
    "tagline": "iOS Optimization • Particle VFX • Arcade Physics",
    "date": "2021-11",
    "types": [
      "software"
    ],
    "shortDesc": "A fast-paced arcade game for iOS utilizing particle systems and rapid gameplay loops.",
    "longDesc": "Dragon Faya is an iOS-exclusive arcade shooter. My contribution focused on optimizing the Unity engine for Apple devices, implementing performant particle effects (VFX) for fire mechanics, and fine-tuning the difficulty curve to maximize user retention.",
    "coverImage": "images/DragonFaya/DragonFaya-01.jpg",
    "gallery": [
      {
        "type": "image",
        "src": "images/DragonFaya/DragonFaya-01.jpg"
      },
      {
        "type": "image",
        "src": "images/DragonFaya/DragonFaya-02.jpeg"
      },
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=syhsci_zf4U"
      }
    ],
    "links": [
      {
        "label": "App Info",
        "url": "https://appadvice.com/app/dragon-faya/1597632362"
      }
    ]
  },
  {
    "id": "redline-engine-sounds",
    "name": "Redline Engine Sounds",
    "role": "Freelance Developer",
    "tagline": "Unity • C# • Google AdMob • Audio Programming • Android",
    "date": "2021-10",
    "types": [
      "software"
    ],
    "shortDesc": "A sophisticated audio simulation app mimicking supercar engine physics, throttle response, and gear transmission logic.",
    "longDesc": "Developed an immersive acoustic simulation app for automotive enthusiasts, managing the entire lifecycle from concept to deployment as a freelance developer.\n\nKey Technical Achievements:\n\nAudio Engine Development: Engineered a dynamic sound system using C# in Unity. Implemented algorithms that adjust audio Pitch and Volume in real-time based on user input (throttle position), simulating realistic RPM acceleration and deceleration.\n\nMonetization & SDK Integration: Successfully integrated the Google Mobile Ads (AdMob) SDK to generate revenue, implementing both Banner and Interstitial ad formats while maintaining a non-intrusive user experience.\n\nUI/UX Design: Created an interactive dashboard interface featuring functional pedals and responsive tachometers (RPM gauges) to enhance user immersion.\n\nPerformance Optimization: Optimized audio assets and code architecture to ensure smooth performance across a wide range of Android devices.",
    "coverImage": "images/redline-engine-sounds/Redline_Engine_Sounds_icon.jpeg",
    "gallery": [
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=Tp5mlPiPLVs"
      }
    ],
    "links": [
      {
        "label": "Google Play",
        "url": "https://play.google.com/store/apps/details?id=com.Okkagames.RedlineEngineSounds&hl=en"
      }
    ]
  },
  {
    "id": "redline-moto-sounds",
    "name": "Redline Motorcycle Sounds",
    "role": "Freelance Developer",
    "tagline": "Audio Simulation • DSP • Interactive Systems",
    "date": "2021-10",
    "types": [
      "software"
    ],
    "shortDesc": "Specialized acoustic simulation for high-performance motorcycles with rapid throttle response logic.",
    "longDesc": "A standalone expansion of the Redline series focused on the distinct acoustic properties of motorcycle engines. The challenge was to replicate the rapid RPM acceleration and deceleration characteristic of bikes. I developed a responsive throttle control algorithm that provides instant auditory feedback, essential for user immersion.",
    "coverImage": "images/RedlineMotorcycleSounds-Icon.png",
    "gallery": [
      {
        "type": "image",
        "src": "images/RedlineMotorcycleSounds-Icon.png"
      },
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=Tp5mlPiPLVs"
      },
      {
        "type": "image",
        "src": ""
      }
    ],
    "links": [
      {
        "label": "Google Play",
        "url": "https://play.google.com/store/apps/details?id=com.Okka.RedlineMotorcycleSounds&hl=en"
      }
    ]
  },
  {
    "id": "redline-engine-sounds",
    "name": "Redline Engine Sounds",
    "types": [
      "software"
    ],
    "gallery": [
      {
        "type": "youtube",
        "src": "https://www.youtube.com/watch?v=Tp5mlPiPLVs"
      }
    ],
    "links": [
      {
        "label": "Google Play",
        "url": "https://play.google.com/store/apps/details?id=com.Okkagames.RedlineEngineSounds&hl=en"
      }
    ],
    "role": "Freelance Developer",
    "tagline": "Unity • C# • Google AdMob • Audio Programming • Android",
    "date": "2021-10",
    "shortDesc": "A sophisticated audio simulation app mimicking supercar engine physics, throttle response, and gear transmission logic.",
    "longDesc": "Developed an immersive acoustic simulation app for automotive enthusiasts, managing the entire lifecycle from concept to deployment as a freelance developer.\n\nKey Technical Achievements:\n\nAudio Engine Development: Engineered a dynamic sound system using C# in Unity. Implemented algorithms that adjust audio Pitch and Volume in real-time based on user input (throttle position), simulating realistic RPM acceleration and deceleration.\n\nMonetization & SDK Integration: Successfully integrated the Google Mobile Ads (AdMob) SDK to generate revenue, implementing both Banner and Interstitial ad formats while maintaining a non-intrusive user experience.\n\nUI/UX Design: Created an interactive dashboard interface featuring functional pedals and responsive tachometers (RPM gauges) to enhance user immersion.\n\nPerformance Optimization: Optimized audio assets and code architecture to ensure smooth performance across a wide range of Android devices.",
    "coverImage": "images/redline-engine-sounds/Redline_Engine_Sounds_icon.jpeg"
  }
];
